# Generated by Django 6.0 on 2026-01-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decoration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decorationservice',
            name='theme',
        ),
        migrations.AlterField(
            model_name='decorationservice',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='decorationservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
