# Generated by Django 6.0 on 2026-01-11 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decoration', '0002_remove_decorationservice_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decorationservice',
            name='theme',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
