# Generated by Django 6.0 on 2026-02-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_serviceprovideruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceProviderUser',
        ),
    ]
