# Generated by Django 6.0 on 2026-01-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_content_type_booking_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='provider_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
