# Generated by Django 6.0 on 2026-01-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_provider_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='provider_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='target_service_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
