# Generated by Django 6.0 on 2026-01-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_content_type_remove_booking_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='target_service_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='service_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(default='generic', max_length=50),
        ),
    ]
