# Generated by Django 6.0 on 2026-02-01 06:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_review'),
        ('serviceprovider', '0003_service_coverage_type_service_cuisine_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='serviceprovider.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
