# Generated by Django 6.0.1 on 2026-02-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_service_id_booking_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service_type',
        ),
    ]
