# Generated by Django 6.0 on 2026-01-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CateringService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('menu_type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
    ]
