# Generated by Django 6.0 on 2026-01-07 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cateringservice',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='cateringservice',
            name='menu_type',
        ),
        migrations.AddField(
            model_name='cateringservice',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cateringservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
