# Generated by Django 6.0 on 2026-01-07 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0002_remove_cateringservice_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringservice',
            name='menu_type',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Both', 'Both')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
