# Generated by Django 6.0 on 2026-01-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0003_cateringservice_menu_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cateringservice',
            name='description',
        ),
        migrations.AlterField(
            model_name='cateringservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
