# Generated by Django 6.0 on 2026-01-08 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0004_remove_cateringservice_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringservice',
            name='contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cateringservice',
            name='menu_type',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Both', 'Both')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cateringservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
