# Generated by Django 6.0 on 2026-02-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider', '0004_service_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
