# Generated by Django 6.0 on 2026-02-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider', '0005_service_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='coverage_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='cuisine_types',
        ),
        migrations.RemoveField(
            model_name='service',
            name='decoration_style',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='service',
            name='materials_included',
        ),
        migrations.RemoveField(
            model_name='service',
            name='menu_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='package_price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='parking_available',
        ),
        migrations.RemoveField(
            model_name='service',
            name='photographer_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_per_plate',
        ),
        migrations.RemoveField(
            model_name='service',
            name='seating_capacity',
        ),
    ]
