# Generated by Django 6.0 on 2026-02-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider', '0006_remove_service_coverage_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='event_types',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='menu_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
